// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgsfqnngarrgofyskzpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhnc2Zxbm5nYXJyZ29meXNrenBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTY3MzYsImV4cCI6MjA2MDEzMjczNn0.Ruw9OBFHeLbBPWaXIgvrB-Y_HiJ2ZVqUsJ_O0hMKLDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);